# Generated by Django 4.2.25 on 2025-10-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_zenopay_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("zenopay_mobile_money", "ZenoPay Mobile Money"),
                    ("mpesa", "M-Pesa"),
                    ("tigopesa", "Tigo Pesa"),
                    ("airtelmoney", "Airtel Money"),
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                ],
                max_length=20,
            ),
        ),
    ]
