# Generated by Django 4.2.25 on 2025-10-16 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_alter_purchase_payment_method"),
        ("billing", "0004_add_expired_status"),
    ]

    operations = []
