# Generated by Django 5.2.7 on 2025-10-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_merge_20251016_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('vodacom', 'Vodacom M-Pesa'), ('halotel', 'Halotel'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money')], help_text='Mobile money provider for payment', max_length=20),
        ),
    ]
