# Generated by Django 5.2.7 on 2025-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_add_mobile_money_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='smspackage',
            name='allowed_sender_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed sender IDs for this package'),
        ),
        migrations.AddField(
            model_name='smspackage',
            name='default_sender_id',
            field=models.CharField(blank=True, help_text='Default sender ID for this package (e.g., Taarifa-SMS, Quantum)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smspackage',
            name='sender_id_restriction',
            field=models.CharField(choices=[('none', 'No Restriction'), ('default_only', 'Default Sender ID Only'), ('allowed_list', 'Allowed List Only'), ('custom_only', 'Custom Sender IDs Only')], default='none', help_text='Sender ID restriction policy', max_length=20),
        ),
    ]
