# Generated by Django 5.2.7 on 2025-10-18 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_sender_id_to_sms_package'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSMSPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.PositiveIntegerField(help_text='Number of SMS credits (minimum 100)')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per SMS in TZS', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price in TZS', max_digits=10)),
                ('active_tier', models.CharField(help_text="Active pricing tier (e.g., 'Lite', 'Standard')", max_length=50)),
                ('tier_min_credits', models.PositiveIntegerField(help_text='Minimum credits for this tier')),
                ('tier_max_credits', models.PositiveIntegerField(help_text='Maximum credits for this tier')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_sms_purchase', to='billing.paymenttransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sms_purchases', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sms_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_sms_purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
