# Generated by Django 5.2.7 on 2025-10-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_customsmspurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsmspurchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='user',
        ),
    ]
