# Generated by Django 5.2.7 on 2025-10-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_add_user_to_usage_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsmspurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
