# Generated by Django 5.2.7 on 2025-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspackage',
            name='package_type',
            field=models.CharField(choices=[('lite', 'Lite'), ('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smspackage',
            name='sender_id_restriction',
            field=models.CharField(choices=[('none', 'No Restriction'), ('default_only', 'Default Sender ID Only'), ('allowed_list', 'Allowed List Only')], default='none', help_text='Sender ID restriction policy', max_length=20),
        ),
    ]
