# Generated by Django 5.2.7 on 2025-10-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_remove_custom_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smspackage',
            name='package_type',
            field=models.CharField(choices=[('lite', 'Lite'), ('standard', 'Standard'), ('pro', 'Pro')], max_length=20),
        ),
    ]
