# Generated by Django 5.2.7 on 2025-10-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invitation_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
