# Generated by Django 4.2.1 on 2025-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="api_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
