# Generated by Django 5.2.7 on 2025-10-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_security_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauth',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecurityEvent',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
