# Generated by Django 4.2.14 on 2025-10-10 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = []
