# Generated by Django 4.2.14 on 2025-10-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0002_contact_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="SenderNameRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        help_text="Sender name (max 11 alphanumeric characters)",
                        max_length=11,
                    ),
                ),
                (
                    "use_case",
                    models.TextField(
                        help_text="Description of how the sender name will be used"
                    ),
                ),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of uploaded supporting document file paths",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("requires_changes", "Requires Changes"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the request"
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_request_id",
                    models.CharField(
                        blank=True, help_text="ID from SMS provider", max_length=100
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_sender_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_name_requests",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "sender_name_requests",
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "sender_name")},
            },
        ),
    ]
