# Generated by Django 4.2.14 on 2025-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_sendernamerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipient_number",
            field=models.CharField(
                blank=True, help_text="Phone number of the recipient", max_length=20
            ),
        ),
    ]
