# Generated by Django 4.2.14 on 2025-10-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0004_message_recipient_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_e164",
            field=models.CharField(max_length=20),
        ),
    ]
