# Generated by Django 4.2.14 on 2025-10-16 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0005_remove_phone_uniqueness"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("created_by", "phone_e164")},
        ),
    ]
