# Generated by Django 5.2.7 on 2025-10-19 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_customsmspurchase_user_and_more'),
        ('messaging', '0006_alter_contact_unique_together'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderIDRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('default', 'Default Sender ID'), ('custom', 'Custom Sender ID')], default='default', max_length=20)),
                ('requested_sender_id', models.CharField(help_text='Requested sender ID (max 11 characters)', max_length=11)),
                ('sample_content', models.TextField(help_text='Sample message content (max 170 characters)', max_length=170)),
                ('business_justification', models.TextField(help_text='Why do you need this sender ID?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sender_id_requests', to=settings.AUTH_USER_MODEL)),
                ('sms_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_id_requests', to='billing.smspackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id_requests', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sender_id_requests',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'requested_sender_id')},
            },
        ),
        migrations.CreateModel(
            name='SenderIDUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('detached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='messaging.senderidrequest')),
                ('sms_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id_usage', to='billing.smspackage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id_usage', to='tenants.tenant')),
            ],
            options={
                'db_table': 'sender_id_usage',
                'ordering': ['-attached_at'],
            },
        ),
    ]
