# Generated by Django 5.2.7 on 2025-10-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_senderidrequest_senderidusage'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('tenant', 'phone_e164')},
        ),
    ]
