# Generated by Django 5.2.7 on 2025-10-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_add_tenant_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderidrequest',
            name='business_justification',
            field=models.TextField(blank=True, help_text='Why do you need this sender ID?', null=True),
        ),
    ]
