# Generated by Django 5.2.7 on 2025-10-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_alter_senderidrequest_business_justification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderidrequest',
            name='business_justification',
        ),
    ]
