# Generated by Django 4.2.25 on 2025-10-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0010_remove_senderidrequest_business_justification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senderidrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("requires_changes", "Requires Changes"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
