# Generated by Django 5.2.7 on 2025-10-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_alter_senderidrequest_status'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('all', 'All Channels')], default='sms', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('promotions', 'Promotions'), ('reminders', 'Reminders'), ('loyalty', 'Loyalty'), ('win_back', 'Win-Back'), ('post_purchase', 'Post-Purchase'), ('authentication', 'Authentication'), ('marketing', 'Marketing'), ('utility', 'Utility'), ('otp', 'One-time password')], max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('fr', 'French'), ('ar', 'Arabic')], default='en', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('tenant', 'name', 'channel')},
        ),
    ]
