# Generated by Django 5.2.7 on 2025-10-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_template_channel_template_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsprovider',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, TZS, KES, NGN)', max_length=10),
        ),
    ]
