# Generated by Django 5.2.7 on 2025-10-25 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Webhook URL to receive notifications')),
                ('events', models.JSONField(default=list, help_text='List of events this webhook should receive')),
                ('is_active', models.BooleanField(default=True)),
                ('total_calls', models.PositiveBigIntegerField(default=0)),
                ('successful_calls', models.PositiveBigIntegerField(default=0)),
                ('failed_calls', models.PositiveBigIntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api_integration.apiaccount')),
            ],
            options={
                'db_table': 'api_webhooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
